project:
  type: website
  output-dir: docs

website:
  title: "Lukas Galke"
  twitter-card:
    creator: "@LukasGalke"
  open-graph: true
  navbar:
    logo: /images/2678287104_unstable_alchemy__digital_art__logo.png
#    left:
#      - href: index.qmd
#        text: Home
    right:
      - icon: "twitter"
        href: https://twitter.com/LukasGalke
      - icon: "mastodon" 
        href: https://sigmoid.social/@lpag
      - icon: "github"
        href: https://github.com/lgalke
      - icon: "journals"
        href: https://scholar.google.de/citations?user=AHGGdYQAAAAJ&hl=en
      
        

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
