project:
  type: website
  output-dir: docs

website:
  title: "Lukas Galke"
  twitter-card:
    creator: "@LukasGalke"
  open-graph: true
  navbar:
    # logo: images/2022-05-Lukas-Galke.jpg
    left:
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Talks
      - href: bio.qmd
        text: Bio
      - href: about.qmd
        text: About
        

format:
  html:
    theme: 
      - litera
      - custom.scss
#    theme: sandstone
#      light:
#        - flatly
#        - custom.scss
#      dark:
#        - darkly
#        - custom.scss
    css: styles.css
    toc: true

execute:
  freeze: auto
