# publications 

## journal articles

- [j7] Lukas Galke, Yoav Ram, Limor Raviv (in prep). [What makes a language easy to deep-learn?](https://arxiv.org/abs/2302.12239)

- [j6] Eva Seidlmayer, Tetyana Melnychuk, Lukas Galke, Lisa Kühnel, Klaus Tochtermann, Carsten Schultz, Konrad Förstner (in prep). Research Topic Displacement and the Lack of Interdisciplinarity: Lessons from the Scientific Response to COVID-19.

- [j5] Lukas Galke, Andor Diera, Bao Xin Lin, Bhakti Khera, Tim Meuser, Tushar Singal, Fabian Karl, Ansgar Scherp (under review). [Are We Really Making Much Progress? Bag-of-Words vs. Sequence vs. Graph vs. Hierarchy for Single-label and Multi-label Text Classification](https://arxiv.org/abs/2204.03954).

- [j4] Tetyana Melnychuk, Lukas Galke, Eva Seidlmayer; Stefanie Bröring, Konrad Förstner, Klaus Tochtermann, Carsten Schultz (revision submitted). Development of Similarity Measures from Graph-Structured Bibliographic Metadata: An Application to Identify Scientific Convergence.

- [j3] Lukas Galke, Iacopo Vagliano, Benedikt Franke, Tobias Zielke, Marcel Hoffmann, Ansgar Scherp (2023). [Lifelong Learning on Evolving Graphs Under the Constraints of Imbalanced Classes and New Classes](https://pure.mpg.de/rest/items/item_3368482_4/component/file_3510107/content). *Neural Networks* 164, 156-176. [https://doi.org/10.1016/j.neunet.2023.04.022](https://doi.org/10.1016/j.neunet.2023.04.022)

- [j2] Iacopo Vagliano, Lukas Galke, Ansgar Scherp (2022). Recommendations for item set completion: on the semantics of item co-occurrence with data sparsity, input size, and input modalities. *Inf Retrieval J* 25, 269–305. [https://doi.org/10.1007/s10791-022-09408-9](https://doi.org/10.1007/s10791-022-09408-9)

- [j1] Tetyana Melnychuk, Lukas Galke, Eva Seidlmayer, Konrad Ulrich Förster, Klaus Tochtermann, Carsten Schultz (2021). Früherkennung wissenschaftlicher Konvergenz im Hochschulmanagement [translated: Early-detection of scientic convergence in university management]. [*Hochschulmanagement* 16(1)](https://www.universitaetsverlagwebler.de/_files/ugd/7bac3c_24fe9adc2e3740178ad5ba98f66d1931.pdf).

## conference papers

- [c11] Marcel Hoffmann, Lukas Galke, Ansgar Scherp (in press). Open-World Lifelong Graph Learning. In *International Joint Conference on Neural Networks (IJCNN)*. IEEE.

- [c10] Lukas Galke, Isabelle Cuber, Christoph Meyer, Henrik Ferdinand Nölscher, Angelina Sonderecker, Ansgar Scherp (2022). General Cross-Architecture Distillation of Pretrained Language Models into Matrix Embeddings. In *2022 International Joint Conference on Neural Networks (IJCNN)*. IEEE. [https://doi.org/10.1109/IJCNN55064.2022.9892144](https://10.1109/IJCNN55064.2022.9892144)

- [c9] Lukas Galke, Ansgar Scherp (2022). [Bag-of-Words vs. Graph vs. Sequence in Text Classification: Questioning the Necessity of Text-Graphs and the Surprising Strength of a Wide MLP](https://doi.org/10.18653/v1/2022.acl-long.279). In *Proceedings of the 60th Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers)*, pages 4038–4051, Dublin, Ireland. Association for Computational Linguistics. [https://doi.org/10.18653/v1/2022.acl-long.279](https://doi.org/10.18653/v1/2022.acl-long.279)

- [c8] Lukas Galke, Benedikt Franke, Tobias Zielke, Ansgar Scherp (2021). Lifelong Learning of Graph Neural Networks for Open-World Node Classication. In *2021 International Joint Conference on Neural Networks (IJCNN)*. IEEE. [https://doi.org/10.1109/IJCNN52387.2021.9533412](https://doi.org/10.1109/IJCNN52387.2021.9533412)

- [c7] Lukas Galke, Tetyana Melnychuk, Eva Seidlmayer, Steffen Trog, Konrad U. Förster, Carsten Schultz, Klaus Tochtermann (2019). [Inductive Learning of Concept Representations from Library-Scale Bibliographic Corpora](https://dl.gi.de/handle/20.500.12116/24973). In: *INFORMATIK 2019*. GI. [https://doi.org/10.18420/inf2019_26](https://doi.org/10.18420/inf2019_26)

- [c6] Florian Mai, Lukas Galke, Ansgar Scherp (2019). [CBOW Is Not All You Need: Combining CBOW with the Compositional Matrix Space Model](https://openreview.net/pdf?id=H1MgjoR9tQ). In *International Conference on Learning Representations (ICLR)*. OpenReview.net.

- [c5] Ahmed Saleh, Tilman Beck, Lukas Galke, Ansgar Scherp (2018). Performance of Ad-Hoc Retrieval Models over Full-Text vs. Titles of Documents. In *International Conference on Asian Digital Libraries (ICADL)*.

- [c4] Lukas Galke, Florian Mai, Iacopo Vagliano, Ansgar Scherp (2018). Multi-Modal Adversarial Autoencoders for Recommendation of Citations and Subject Labels. In *Conference on User Modeling, Adaptation and Personalization (UMAP)*. ACM. [https://doi.org/10.1145/3209219.3209236](https://doi.org/10.1145/3209219.3209236)

- [c3] Anne Lauscher, Kai Eckert, Lukas Galke, Ansgar Scherp, Syed Tassen Raza Rizvi, Sheraz Ahmed, Andreas Dengel, Philipp Zumstein, Annette Klein (2018). Linked Open Citation Database: Enabling Libraries to Contribute to an Open and Interconnected Citation Graph. In *Joint Conference on Digital Libraries (JCDL)*. ACM.

- [c2] Florian Mai, Lukas Galke, Ansgar Scherp (2018). Using Deep Learning for Title-Based Semantic Subject Indexing to Reach Competitive Performance to Full-Text. In *Joint Conference on Digital Libraries (JCDL)*. ACM. [https://doi.org/10.1145/3197026.3197039](https://doi.org/10.1145/3197026.3197039)

- [c1] Lukas Galke, Florian Mai, Alan Schelten, Dennis Brunch, Ansgar Scherp (2017). Using Titles vs. Full-text as Source for Automated Semantic Document Annotation. In *Knowledge Capture Conference (K-CAP)*. ACM. [https://doi.org/10.1145/3148011.3148039](https://doi.org/10.1145/3148011.3148039)

## workshop papers

- [w8] Lukas Galke, Yoav Ram, Limor Raviv (2022). Emergent communication for understanding human language evolution: What's missing?. Emergent Communication workshop at *The Tenth International Conference on Learning Representations (ICLR 2022)*.OpenReview.net. [https://openreview.net/forum?id=rqUGZQ-0XZ5](https://openreview.net/forum?id=rqUGZQ-0XZ5)

- [w7] Lukas Galke, Eva Seidlmayer, Gavin Lüdemann, Lisa Langnickel, Tetyana Melnychuk, Konrad U Förstner, Klaus Tochtermann, Carsten Schultz (2021). COVID-19++: A Citation-Aware Covid-19 Dataset for the Analysis of Research Dynamics. In *2021 IEEE International Conference on Big Data (Big Data)*. IEEE.

- [w6] Eva Seidlmayer, Jakob Voß, Tatyana Melnychuk, Lukas Galke, Klaus Tochtermann, Carsten Schultz, Konrad U. Förstner: ORCID for Wikidata — Data enrichment for scientometric applications, Wikidata workshop @ *ISWC 2020*.

- [w5] Eva Seidlmayer, Lukas Galke, Tatyana Melnychuk, Carsten Schultz, Klaus Tochtermann, Konrad U. Förstner (2019): Take it Personally — A Python library for enrichment in informetrical applications. Posters&Demos @ *SEMANTICS 2019*.

- [w4] Lukas Galke, Iacopo Vagliano, Ansgar Scherp (2019). Can Graph Neural Networks Go „Online“? An Analysis of Pretraining and Inference. Representation Learning on Graphs and Manifolds workshop @ *ICLR 2019*.

- [w3] Iacopo Vagliano, Lukas Galke, Florian Mai, Ansgar Scherp (2018). Using Adversarial Autoencoders for Multi-Modal Automatic Playlist Continuation. RecSys Challenge workshop @ *RecSys'18*.

- [w2] Lukas Galke, Gunnar Gerstenkorn, Ansgar Scherp (2018). A Case Study of Closed-Domain Response Suggestion with Limited Training Data. Text-based Information Retrieval workshop @ *DEXA'18*.

- [w1] Lukas Galke, Ahmed Saleh, Ansgar Scherp (2017). Word Embeddings for Practical Information Retrieval. In *INFORMATIK 2017*. Gesellschaft für Informatik, Bonn. (S. 2155-2167). [https://doi.org/10.18420/in2017_215](https://doi.org/10.18420/in2017_215)

## (extended) abstracts

- [a2] Lukas Galke (2022). Representation Learning for Texts and Graphs: A Unified Perspective On Efficiency, Multimodality, and Adaptability [selected PhD thesis abstract]. *IEEE Intelligent Informatics Bulletin*, 22(1), 52. [https://www.comp.hkbu.edu.hk/~cib/2022/IIB2022_Final.pdf](https://www.comp.hkbu.edu.hk/~cib/2022/IIB2022_Final.pdf)

- [a1] Lukas Galke, Florian Mai, Ansgar Scherp (2019): What If We Encoded Words as Matrices and Used Matrix Multiplication as Composition Function [extended abstract]. INFORMATIK 2019. GI.

## thesis

- Lukas Galke (2023). Representation Learning for Texts and Graphs: A Unified Perspective On Efficiency, Multimodality, and Adaptability. Number 2023/1 in Kiel Computer Science Series. Department of Computer Science, 2023. Dissertation, Faculty of Engineering, Kiel University. [https://doi.org/10.21941/kcss/2023/1](https://doi.org/10.21941/kcss/2023/1)

