---
title: Talks
---

## Invited talks in colloquia and seminars

- [t29] Lukas Galke (2023, July 20). *What makes a language easy to deep-learn?* [invited talk]. Colloquium Cognitive Systems, University of Ulm, Germany.
- [t28] Lukas Galke (2023, July 10). *Lifelong Learning and Out-of-distribution Detection on Evolving Graphs* [invited talk], VU AI Colloquium, Amsterdam, The Netherlands.
- [t25] Lukas Galke (2023, May 16). *What makes a language easy to deep-learn?* [invited talk]. Computational Linguistics Seminar, University of Amsterdam, The Netherlands.

## Informal talks

- [t27] Lukas Galke (2023, July 5). *Lifelong Neural Communication* [informal talk]. Data Science, Hamburg University, Germany.
- [t26] Lukas Galke (2023, May 17). *Uncovering Patterns in Medical Literature through Lifelong Automated Categorization and Research Dynamics Analysis with Machine Learning* [informal talk]. KIK AI Coffee & Learning meeting, Amsterdam University Medical Centre, The Netherlands.
- [t24] Lukas Galke (2023, February 27). *What makes a language easy to deep learn?* [informal talk]. Language Evolution and Emergence meeting, Max Planck Institute for Psycholinguistics, Nijmegen, The Netherlands.
- [t23] Lukas Galke (2022, October 20). *Structure in Language Learning Systems* [informal talk]. TALEP Marseille, France.
- [t13] Lukas Galke (2020, June 23). *Scaling Up Graph Neural Networks* [literature review talk], Graph Neural Networks Reading Group, online.

## Conference and workshop presentations

- [t30] Lukas Galke (2023, September 28). What makes a language easy to deep-learn? Protolang 8, Rome, Italy. [upcoming talk]
- [t22] Lukas Galke (2022, September 5). *Machine Learning for Language Evolution -- What's missing?*. Machine Learning and the Evolution of Language (ml4evolang) workshop at JCOLE'22, Japan/online.
- [t19] Lukas Galke (2022, July 19). *General Cross-Architecture Distillation of Pretrained Language Models into Matrix Embeddings* [paper presentation (oral)]. World Congress on Computational Intelligence, Padua, Italy.
- [t18] Lukas Galke (2022, June 1). *Emergent Communication for Understanding Human Language Evolution: What’s missing?* [paper presentation (poster)]. IMPRS conference, Nijmegen, The Netherlands.
- [t17] Lukas Galke (2022, May 24). *Bag-of-Words vs. Graph vs. Sequence in Text Classification: Questioning the Necessity of Text-Graphs and the Surprising Strength of a Wide MLP* [paper presentation (oral)]. ACL 2022. [video](https://doi.org/10.48448/09t2-ck98)
- [t16] Lukas Galke (2022, April 29). *Emergent Communication for Understanding Human Language Evolution* [paper presentation (oral) and discussion session]. EmeCom workshop at ICLR'22, online.
- [t15] Lukas Galke (2021, December 15). *COVID-19++: A Citation-Aware Covid-19 Dataset for the Analysis of Research Dynamics* [paper presentation (oral)]. 2021 IEEE International Conference on Big Data (Big Data), online.
- [t14] Lukas Galke (2021, July 18). *Lifelong learning of graph neural networks for open-world node classification* [paper presentation (oral)]. International Joint Conference on Neural Networks, online.
- [t12] Lukas Galke (2019, September 26). *Inductive Learning of Concept Representations from Library-Scale Corpora with Graph Convolution* [paper presentation (oral)], INFORMATIK 2019, Kassel, Germany.
- [t11] Lukas Galke (2019, September 26). *What If We Encoded Words as Matrices and Used Matrix Multiplication as Composition Function* [paper presentation (oral)]. INFORMATIK 2019, Kassel, Germany
- [t10] Lukas Galke, Florian Mai (2019, May 8). *CBOW Is Not All You Need: Combining CBOW with the Compositional Matrix Space Model* [paper presentation (poster)]. International Conference on Learning Representations, New Orleans, Lousiana.
- [t9] Lukas Galke (2019, May 7). *Can Graph Neural Networks Go Online? An Analysis of Pretraining and Inference* [paper presentation (poster)]. International Conference on Learning Representations, New Orleans, Lousiana.
- [t8] Anne Lauscher, Lukas Galke, Syed Tahseen Raza Rizvi (2018, November 6). LOC-DB Evaluation: criteria and preliminary results. Second Linked Open Citation Database (LOC-DB) workshop. [project presentation]
- [t7] Lukas Galke (2018, July 10). *Multi-Modal Adversarial Autoencoders for Recommendations of Citations and Subject Labels* [paper presentation (oral)]. Conference on User Modeling, Adaptation and Personalization, Singapore, Singapore.
- [t6] Lukas Galke (2017, December 6). *Using Titles vs. Full-text as Source for Automated Semantic Document Annotation* [paper presentation (oral)], Knowledge Capture Conference, Austin, Texas.
- [t5] Kai Eckert, Anne Lauscher, Lukas Galke (2017, November 7). LOC-DB Konzepte. First Linked Open Citation Database (LOC-DB) Workshop. [project presentation]
- [t4] Lukas Galke (2017, September 28). *Reranking-based Recommender Systems with Deep Learning* [paper presentation (oral)]. INFORMATIK 2017, Chemnitz, Germany.
- [t3] Lukas Galke (2017, September 28). *Word Embeddings for Practical Information Retrieval* [paper presentation (oral)]. INFORMATIK 2017, Chemnitz, Germany.
- [t2] Lukas Galke (2017, May 5). *Embedded Retrieval: Word Embeddings for Practical Information Retrieval* [M.Sc. thesis presentation]. Second DyESE workshop, Kiel, Germany.
- [t1] Lukas Galke (2016, September 16). *Information Retrieval on Sparse Data* [concept presentation]. First DyESE workshop, Oslo, Norway.

## Other

- [t21] Lukas Galke (2022, August 28). *Representation Learning for Texts and Graphs* [viva]. Department of Computer Science, Kiel University, Germany.
- [t20] Lukas Galke (2022, August 18). *Language Technology* [gave a 2x45min workshop]. Regiodag 2022 Probusclub Nijmegen e.o., Nijmegen, The Netherlands.
